# Generated by Django 4.0.4 on 2022-04-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.category')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.priority')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='priority',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.user'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=500)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.user'),
        ),
    ]
